Docker - Elasticsearch6 - Add additional helper methods for xpack_security

diff --git a/docker/templates/searchindexers/elasticsearch6/dockerelasticsearch6 b/docker/templates/searchindexers/elasticsearch6/dockerelasticsearch6
--- a/docker/templates/searchindexers/elasticsearch6/dockerelasticsearch6
+++ b/docker/templates/searchindexers/elasticsearch6/dockerelasticsearch6
@@ -13,6 +13,11 @@ dockerelasticsearch6() {
 	# @output varies, depending on the command used
 
 	local scriptpath="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+	local scriptpath_escaped="$(echo "${scriptpath}" | awk '{gsub(/ /,"\\ ");print}')"
+
+	# Default Elasticsearch - User
+	local elasticsearch_xpack_username="elastic"
+	local elasticsearch_xpack_password="pleasechangeme"
 
 	# Dockerfile
 	# FROM docker.elastic.co/elasticsearch/elasticsearch:6.1.3
@@ -25,6 +30,8 @@ dockerelasticsearch6() {
 	local container_name="ldt_elasticsearch_6"
 	local container_cmd=""
 	local container_options=(
+		"-v ${scriptpath_escaped}/config/x-pack/certificates/certs:/usr/share/elasticsearch/config/x-pack/certificates/certs:ro"
+		"-e ELASTIC_PASSWORD=${elasticsearch_xpack_password}"
 		"-e discovery.type=single-node"
 		"-e cluster.name=LiferayElasticsearchCluster"
 		"-e network.host=_local_"
@@ -37,14 +44,98 @@ dockerelasticsearch6() {
 		"-p 9300:9300"
 	)
 
+	local container_xpack_security_options=(
+		"-e xpack.license.self_generated.type=trial"
+		"-e xpack.security.transport.ssl.verification_mode=certificate"
+		"-e xpack.ssl.certificate_authorities=/usr/share/elasticsearch/config/x-pack/certificates/certs/server.crt"
+		"-e xpack.ssl.certificate=/usr/share/elasticsearch/config/x-pack/certificates/certs/server.crt"
+		"-e xpack.ssl.key=/usr/share/elasticsearch/config/x-pack/certificates/certs/server.key"
+	)
+
+	local elasticsearch_configuration_additional_options=(
+		"xpack.security.enabled: false"
+		"xpack.security.http.ssl.enabled: false"
+		"xpack.security.transport.ssl.enabled: false"
+	)
+
 	if [ -n "$1" ]; then
 		case "$1" in
+			'enable_xpack_security')
+				if (dockercontainer 'is_running' "${container_name}"); then
+					if (! dockerelasticsearch6 'is_xpack_security_enabled'); then
+						local enable_xpack_security_options=(
+							"sed -i 's/xpack.security.enabled: false/xpack.security.enabled: true/' config/elasticsearch.yml"
+							"sed -i 's/xpack.security.http.ssl.enabled: false/xpack.security.http.ssl.enabled: true/' config/elasticsearch.yml"
+							"sed -i 's/xpack.security.transport.ssl.enabled: false: false/xpack.security.transport.ssl.enabled: false: true/' config/elasticsearch.yml"
+						)
+
+						local enable_xpack_security_options_delimited"=$(dockerutil array_to_string_delimited ';' "${enable_xpack_security_options[@]}")"
+
+						echo "INFO: enabling xpack security.."
+						dockercontainer exec "${container_name}" bash -c "${enable_xpack_security_options_delimited}"
+						
+						echo 'INFO: restarting elasticsearch..'
+						dockerelasticsearch6 'restart'
+					else
+						echo "INFO: xpack security is already enabled."
+					fi
+				else
+					echo "ERROR: Elasticsearch container is not running."
+				fi;;
+			'disable_xpack_security')
+				if (dockercontainer 'is_running' "${container_name}"); then
+					if (dockerelasticsearch6 'is_xpack_security_enabled'); then
+						local disable_xpack_security_options=(
+							"sed -i 's/xpack.security.enabled: true/xpack.security.enabled: false/' config/elasticsearch.yml"
+							"sed -i 's/xpack.security.http.ssl.enabled: true/xpack.security.http.ssl.enabled: false/' config/elasticsearch.yml"
+							"sed -i 's/xpack.security.transport.ssl.enabled: true/xpack.security.transport.ssl.enabled: false/' config/elasticsearch.yml"
+						)
+
+						local disable_xpack_security_options_delimited"=$(dockerutil array_to_string_delimited ';' "${disable_xpack_security_options[@]}")"
+
+						echo "INFO: disabling xpack security.."
+						dockercontainer exec "${container_name}" bash -c "${disable_xpack_security_options_delimited}"
+						
+						echo 'INFO: restarting elasticsearch..'
+						dockerelasticsearch6 'restart'
+					else
+						echo "INFO: xpack security is already disabled."
+					fi
+				else
+					echo "ERROR: Elasticsearch container is not running."
+				fi;;
+			'is_xpack_security_enabled')
+				if (dockercontainer 'is_running' "${container_name}"); then
+					if [ $(dockercontainer exec "${container_name}" grep -e "xpack.security.enabled: true" config/elasticsearch.yml | wc -l) -eq 1 ]; then
+						return 0
+					fi
+				fi
+
+				return 1;;
 			'recreate'|'run'|'start')
 				if (! (dockerutil docker_image_exists "${dockerfile_image_name}")); then
 					docker build -t "${dockerfile_image_name}" "${scriptpath}"
 				fi
 
-				dockercontainer "$1" "${container_name}" "${docker_image}" "${container_cmd}" "${container_options[@]}";;
+				local init_elastic
+
+				if [ "$1" == 'recreate' ] || (! dockercontainer 'exists' "${container_name}"); then
+					init_elastic=1
+				fi
+
+				dockercontainer "$1" "${container_name}" "${docker_image}" "${container_cmd}" "${container_options[@]}" "${container_xpack_security_options[@]}"
+
+				if (dockercontainer 'exists' "${container_name}") && [ "${init_elastic}" == "1" ]; then
+					echo 'INFO: setting up intial configuration..'
+
+					local configuration_additional_options_delimited"=$(dockerutil array_to_string_delimited '\\n' "${elasticsearch_configuration_additional_options[@]}")"
+
+					dockercontainer exec "${container_name}" bash -c 'awk -v options="'"${configuration_additional_options_delimited//\"/\\\"}"'" '\''BEGIN{print options}'\'' >> /usr/share/elasticsearch/config/elasticsearch.yml'
+
+					echo 'INFO: restarting elasticsearch..'
+					dockerelasticsearch6 'restart'
+
+				fi;;
 			*)
 				dockercontainer "$1" "${container_name}" "${@:2:${#}}";;
 		esac
